name: 03.04 - Vulnrabilities Scanner
on:
  pull_request:
    branches:
      - main
  
jobs:
  build:
    name: Vulnerabilities-Scanner - 03.04
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run vulnerabilities scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: "fs"
        format: 'table'
        ignore-unfixed: true
        scanners: 'vuln'
        exit-code: '1'
        severity: 'CRITICAL,HIGH,MEDIUM'
  
